[package]
authors = ["HansNK"]
description = "PLACEHOLDER DESCRIPTION"
edition = "2021"
name = "rust_gpu_ml"
version = "0.0.0"

[dependencies]
wgpu="22.1.0"
winit="0.29"
cfg-if="1"
env_logger="0.11"
log="0.4"
web-time="0.2.4"
pollster="0.3"
nanorand="0.7"
png="0.17.11"
bytemuck="1.18"
